-- =========================================================================
-- DATA PRODUCT: Revenue Assurance & Billing Reconciliation Product
-- DOMAIN: Insurance & Financial Services (Billing & Collections)
-- REGION: europe-west1
-- SYNTAX VERSION: v1
-- =========================================================================

-- 1. Create the Dataset (Schema) if it does not exist
CREATE SCHEMA IF NOT EXISTS `billing_reconciliation_prod_v1`
OPTIONS (
  location = 'europe-west1',
  description = 'Data product serving the Revenue Assurance & Billing Reconciliation Business Object. Reconciles expected policy premium invoices against actual payment gateway settlement events.'
);

-- 2. Create Table: billing_invoices
-- Represents expected charges generated by the Policy Administration System (PAS)
CREATE TABLE IF NOT EXISTS `billing_reconciliation_prod_v1`.`billing_invoices` (
  invoice_id STRING NOT NULL OPTIONS(description = 'Unique natural identifier of the premium invoice.'),
  policy_id STRING NOT NULL OPTIONS(description = 'Reference key to the originating Insurance Policy contract.'),
  customer_id STRING NOT NULL OPTIONS(description = 'Reference key to the insured Party or Customer Account.'),
  invoice_date DATE NOT NULL OPTIONS(description = 'The date the premium invoice was officially issued.'),
  due_date DATE NOT NULL OPTIONS(description = 'The contractual payment deadline for the premium.'),
  expected_premium_amount NUMERIC NOT NULL OPTIONS(description = 'Net premium charge expected based on policy coverage terms.'),
  tax_amount NUMERIC NOT NULL OPTIONS(description = 'Tax surcharge applied to the base premium amount.'),
  total_amount_due NUMERIC NOT NULL OPTIONS(description = 'Total gross invoice amount due (premium + tax).'),
  currency STRING NOT NULL OPTIONS(description = 'ISO 4217 currency code (e.g., EUR).'),
  billing_status STRING NOT NULL OPTIONS(description = 'Life cycle status of the invoice: ISSUED, PAID, PARTIALLY_PAID, OVERDUE.'),
  PRIMARY KEY (invoice_id) NOT ENFORCED
)
OPTIONS (
  description = 'Source of truth for expected receivables generated by policy terms, requiring cash settlement reconciliation.'
);

-- 3. Create Table: payments_received
-- Represents cash settlement notifications received from banking and credit card gateways
CREATE TABLE IF NOT EXISTS `billing_reconciliation_prod_v1`.`payments_received` (
  payment_id STRING NOT NULL OPTIONS(description = 'Unique identifier of the financial transaction event.'),
  invoice_id STRING NOT NULL OPTIONS(description = 'The target invoice ID declared or matched during payment capture.'),
  payment_date DATE NOT NULL OPTIONS(description = 'The date the payment transaction cleared successfully.'),
  amount_paid NUMERIC NOT NULL OPTIONS(description = 'The total amount received and settled by the payment processor.'),
  payment_method STRING NOT NULL OPTIONS(description = 'Payment instrument used: DIRECT_DEBIT, CREDIT_CARD, BANK_TRANSFER.'),
  payment_reference STRING NOT NULL OPTIONS(description = 'Gateway transaction hash reference used for tracing.'),
  payment_status STRING NOT NULL OPTIONS(description = 'Financial settlement outcome: COMPLETED, FAILED, REFUNDED.'),
  PRIMARY KEY (payment_id) NOT ENFORCED,
  CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id) REFERENCES `billing_reconciliation_prod_v1`.`billing_invoices`(invoice_id) NOT ENFORCED
)
OPTIONS (
  description = 'Register of incoming liquid cash clearing activities corresponding to policy invoices.'
);

-- 4. Create Table: reconciliation_ledger
-- Analytical fact table resolving differences between expected and received premiums
CREATE TABLE IF NOT EXISTS `billing_reconciliation_prod_v1`.`reconciliation_ledger` (
  reconciliation_id STRING NOT NULL OPTIONS(description = 'Unique identifier of the matching event.'),
  invoice_id STRING NOT NULL OPTIONS(description = 'Reference to the billing invoice being audited.'),
  payment_id STRING OPTIONS(description = 'Reference to the cleared payment transaction if matched.'),
  reconciled_at TIMESTAMP NOT NULL OPTIONS(description = 'Timestamp when the automated reconciliation routine was executed.'),
  variance_amount NUMERIC NOT NULL OPTIONS(description = 'Reconciliation variance calculated as (total_amount_due - amount_paid).'),
  reconciliation_status STRING NOT NULL OPTIONS(description = 'Operational match classification: MATCHED, DISCREPANCY_UNDERPAID, DISCREPANCY_OVERPAID, UNMATCHED_INVOICE, PENDING_MATCH.'),
  resolution_action STRING NOT NULL OPTIONS(description = 'Corrective mitigation path: NONE, WRITE_OFF, ESCALATED_TO_COLLECTIONS, PENDING_INVESTIGATION.'),
  PRIMARY KEY (reconciliation_id) NOT ENFORCED,
  CONSTRAINT fk_rec_invoice FOREIGN KEY (invoice_id) REFERENCES `billing_reconciliation_prod_v1`.`billing_invoices`(invoice_id) NOT ENFORCED,
  CONSTRAINT fk_rec_payment FOREIGN KEY (payment_id) REFERENCES `billing_reconciliation_prod_v1`.`payments_received`(payment_id) NOT ENFORCED
)
OPTIONS (
  description = 'Reconciliation outcome ledger that maps expected billing to actual payments, highlighting exposure and revenue leaks.'
);


-- =========================================================================
-- 5. Seed Realistic Mock Data (105 Rows per table to simulate real ledger states)
-- =========================================================================

-- Seed billing_invoices
INSERT INTO `billing_reconciliation_prod_v1`.`billing_invoices` (
  invoice_id, policy_id, customer_id, invoice_date, due_date, expected_premium_amount, tax_amount, total_amount_due, currency, billing_status
)
SELECT
  CONCAT('INV-', LPAD(CAST(idx AS STRING), 5, '0')) AS invoice_id,
  CONCAT('POL-', LPAD(CAST(1000 + MOD(idx, 30) AS STRING), 5, '0')) AS policy_id,
  CONCAT('CUST-', LPAD(CAST(5000 + MOD(idx, 25) AS STRING), 5, '0')) AS customer_id,
  DATE_SUB(CURRENT_DATE(), INTERVAL MOD(idx, 60) DAY) AS invoice_date,
  DATE_ADD(DATE_SUB(CURRENT_DATE(), INTERVAL MOD(idx, 60) DAY), INTERVAL 30 DAY) AS due_date,
  CAST(ROUND(100.0 + MOD(idx * 17, 400), 2) AS NUMERIC) AS expected_premium_amount,
  CAST(ROUND((100.0 + MOD(idx * 17, 400)) * 0.05, 2) AS NUMERIC) AS tax_amount,
  CAST(ROUND((100.0 + MOD(idx * 17, 400)) * 1.05, 2) AS NUMERIC) AS total_amount_due,
  'EUR' AS currency,
  CASE
    WHEN MOD(idx, 10) = 0 THEN 'OVERDUE'
    WHEN MOD(idx, 10) = 1 THEN 'PARTIALLY_PAID'
    WHEN MOD(idx, 10) = 2 THEN 'ISSUED'
    ELSE 'PAID'
  END AS billing_status
FROM UNNEST(GENERATE_ARRAY(1, 105)) AS idx;


-- Seed payments_received
INSERT INTO `billing_reconciliation_prod_v1`.`payments_received` (
  payment_id, invoice_id, payment_date, amount_paid, payment_method, payment_reference, payment_status
)
SELECT
  CONCAT('PMT-', LPAD(CAST(idx AS STRING), 5, '0')) AS payment_id,
  CONCAT('INV-', LPAD(CAST(idx AS STRING), 5, '0')) AS invoice_id,
  DATE_ADD(DATE_SUB(CURRENT_DATE(), INTERVAL MOD(idx, 60) DAY), INTERVAL MOD(idx * 3, 15) DAY) AS payment_date,
  CAST(
    CASE
      WHEN MOD(idx, 10) = 1 THEN ROUND((100.0 + MOD(idx * 17, 400)) * 1.05 * 0.5, 2) -- Simulate 50% partial payment
      WHEN MOD(idx, 10) = 0 THEN 0.0 -- Unpaid / Overdue
      WHEN MOD(idx, 10) = 2 THEN 0.0 -- Unpaid / Issued
      ELSE ROUND((100.0 + MOD(idx * 17, 400)) * 1.05, 2) -- Fully paid match
    END AS NUMERIC
  ) AS amount_paid,
  CASE
    WHEN MOD(idx, 3) = 0 THEN 'DIRECT_DEBIT'
    WHEN MOD(idx, 3) = 1 THEN 'CREDIT_CARD'
    ELSE 'BANK_TRANSFER'
  END AS payment_method,
  -- STREAMING_CHUNK: Converting SHA256 bytes output to hexadecimal string to prevent BigQuery CONCAT type coercion error
  CONCAT('TXN-', SUBSTR(TO_HEX(SHA256(CAST(idx AS STRING))), 1, 16)) AS payment_reference,
  CASE
    WHEN MOD(idx, 10) IN (0, 2) THEN 'FAILED'
    ELSE 'COMPLETED'
  END AS payment_status
FROM UNNEST(GENERATE_ARRAY(1, 105)) AS idx
WHERE MOD(idx, 10) != 2; -- Simulates cases where unpaid invoices don't even have a failed transaction event recorded


-- Seed reconciliation_ledger
INSERT INTO `billing_reconciliation_prod_v1`.`reconciliation_ledger` (
  reconciliation_id, invoice_id, payment_id, reconciled_at, variance_amount, reconciliation_status, resolution_action
)
SELECT
  CONCAT('REC-', LPAD(CAST(inv.idx AS STRING), 5, '0')) AS reconciliation_id,
  inv.invoice_id,
  pmt.payment_id,
  CURRENT_TIMESTAMP() AS reconciled_at,
  CAST(ROUND(inv.total_amount_due - COALESCE(pmt.amount_paid, 0.0), 2) AS NUMERIC) AS variance_amount,
  CASE
    WHEN pmt.payment_id IS NULL AND inv.billing_status = 'OVERDUE' THEN 'UNMATCHED_INVOICE'
    WHEN pmt.payment_id IS NULL THEN 'PENDING_MATCH'
    WHEN ROUND(inv.total_amount_due - pmt.amount_paid, 2) = 0.0 THEN 'MATCHED'
    WHEN ROUND(inv.total_amount_due - pmt.amount_paid, 2) > 0.0 THEN 'DISCREPANCY_UNDERPAID'
    ELSE 'DISCREPANCY_OVERPAID'
  END AS reconciliation_status,
  CASE
    WHEN ROUND(inv.total_amount_due - COALESCE(pmt.amount_paid, 0.0), 2) = 0.0 THEN 'NONE'
    WHEN inv.billing_status = 'OVERDUE' AND pmt.payment_id IS NULL THEN 'ESCALATED_TO_COLLECTIONS'
    WHEN ROUND(inv.total_amount_due - pmt.amount_paid, 2) > 0.0 THEN 'PENDING_INVESTIGATION'
    ELSE 'WRITE_OFF'
  END AS resolution_action
FROM (
  SELECT *, ROW_NUMBER() OVER(ORDER BY invoice_id) AS idx 
  FROM `billing_reconciliation_prod_v1`.`billing_invoices`
) inv
LEFT JOIN `billing_reconciliation_prod_v1`.`payments_received` pmt
  ON inv.invoice_id = pmt.invoice_id;