-- Create Dataset if it does not exist
CREATE SCHEMA IF NOT EXISTS `scenario_simulation_v1`
OPTIONS(
  location="europe-west1",
  description="Data product containing sandboxes for scenario simulation and predictive forecasting within the financial/insurance domain."
);

-- =======================================================================================
-- Table: scenario_simulation_v1.Simulation_Run
-- Description: Represents a distinct execution of a predictive model or scenario simulation.
-- =======================================================================================
CREATE TABLE IF NOT EXISTS `scenario_simulation_v1.Simulation_Run` (
    Simulation_Run_ID STRING NOT NULL OPTIONS(description="Primary Key. Unique identifier for the simulation run."),
    Model_ID STRING NOT NULL OPTIONS(description="Identifier of the model used for the simulation (e.g., 'Risk_Model_V2', 'Pricing_Elasticity')."),
    Scenario_Name STRING NOT NULL OPTIONS(description="Name or description of the scenario being simulated (e.g., 'Base Case', 'Severe Economic Downturn', 'High Inflation')."),
    Run_Timestamp TIMESTAMP NOT NULL OPTIONS(description="Timestamp when the simulation was executed."),
    Run_By_User_ID STRING OPTIONS(description="Identifier of the user or system process that initiated the run."),
    Status STRING NOT NULL OPTIONS(description="Status of the simulation (e.g., 'Completed', 'Failed', 'In Progress')."),
    Parameters_JSON STRING OPTIONS(description="JSON string capturing the specific parameters and assumptions used for this run."),
    PRIMARY KEY (Simulation_Run_ID) NOT ENFORCED
) OPTIONS(
    description="Core entity representing individual executions of scenario simulations or predictive forecasts."
);

-- =======================================================================================
-- Table: scenario_simulation_v1.Forecast_Metric
-- Description: Stores the resulting metrics and projected values from a simulation run.
-- =======================================================================================
CREATE TABLE IF NOT EXISTS `scenario_simulation_v1.Forecast_Metric` (
    Metric_ID STRING NOT NULL OPTIONS(description="Primary Key. Unique identifier for this specific forecasted metric data point."),
    Simulation_Run_ID STRING NOT NULL OPTIONS(description="Foreign Key linking to the Simulation_Run that produced this metric."),
    Metric_Name STRING NOT NULL OPTIONS(description="Name of the metric being forecasted (e.g., 'Projected_Loss_Ratio', 'Capital_Requirement', 'Expected_Claims')."),
    Projection_Date DATE NOT NULL OPTIONS(description="The future date or period to which the forecasted metric applies."),
    Metric_Value FLOAT64 NOT NULL OPTIONS(description="The calculated numerical value of the forecast."),
    Confidence_Interval_Lower FLOAT64 OPTIONS(description="The lower bound of the confidence interval for the forecast, if applicable."),
    Confidence_Interval_Upper FLOAT64 OPTIONS(description="The upper bound of the confidence interval for the forecast, if applicable."),
    Dimension_1_Name STRING OPTIONS(description="Optional name for a breakdown dimension (e.g., 'Line_of_Business')."),
    Dimension_1_Value STRING OPTIONS(description="Value for Dimension 1 (e.g., 'Auto', 'Home')."),
    PRIMARY KEY (Metric_ID) NOT ENFORCED,
    FOREIGN KEY (Simulation_Run_ID) REFERENCES `scenario_simulation_v1.Simulation_Run`(Simulation_Run_ID) NOT ENFORCED
) OPTIONS(
    description="Detailed output metrics generated by the simulation models, broken down by time and optional dimensions."
);

-- =======================================================================================
-- Insert Sample Data: scenario_simulation_v1.Simulation_Run
-- =======================================================================================
INSERT INTO `scenario_simulation_v1.Simulation_Run` (Simulation_Run_ID, Model_ID, Scenario_Name, Run_Timestamp, Run_By_User_ID, Status, Parameters_JSON)
VALUES
('RUN_001', 'Capital_Stress_Test_V1', 'Baseline', TIMESTAMP('2026-05-18 09:00:00'), 'U1001', 'Completed', '{"interest_rate_shock": 0.0, "equity_drop": 0.0}'),
('RUN_002', 'Capital_Stress_Test_V1', 'Adverse_Market', TIMESTAMP('2026-05-18 10:30:00'), 'U1001', 'Completed', '{"interest_rate_shock": 2.5, "equity_drop": 0.30}'),
('RUN_003', 'Capital_Stress_Test_V1', 'Severe_Inflation', TIMESTAMP('2026-05-18 14:15:00'), 'U1002', 'Completed', '{"inflation_rate": 8.0, "claims_inflation_multiplier": 1.2}'),
('RUN_004', 'Claims_Frequency_Forecast', 'Base_Trend', TIMESTAMP('2026-05-19 08:00:00'), 'SYSTEM', 'Completed', '{"seasonality_factor": true, "weather_impact": "normal"}'),
('RUN_005', 'Claims_Frequency_Forecast', 'Extreme_Weather_Event', TIMESTAMP('2026-05-19 08:30:00'), 'U1003', 'Failed', '{"weather_impact": "hurricane_cat_4"}'),
('RUN_006', 'Pricing_Elasticity_Model', 'Target_Margin_15', TIMESTAMP('2026-05-19 11:00:00'), 'U1004', 'Completed', '{"target_margin": 0.15, "competitor_reaction": "moderate"}'),
('RUN_007', 'Pricing_Elasticity_Model', 'Aggressive_Growth', TIMESTAMP('2026-05-19 13:45:00'), 'U1004', 'In Progress', '{"target_margin": 0.05, "marketing_spend_increase": 0.20}'),
('RUN_008', 'Liquidity_Forecast', 'Normal_Operations', TIMESTAMP('2026-05-19 15:00:00'), 'SYSTEM', 'Completed', '{"large_claim_probability": "historical"}'),
('RUN_009', 'Lapse_Rate_Predictor', 'Recession_Scenario', TIMESTAMP('2026-05-18 16:00:00'), 'U1005', 'Completed', '{"unemployment_rate": 10.5, "disposable_income_change": -0.05}'),
('RUN_010', 'Lapse_Rate_Predictor', 'Optimistic_Economy', TIMESTAMP('2026-05-18 16:30:00'), 'U1005', 'Completed', '{"unemployment_rate": 4.0, "disposable_income_change": 0.03}');

-- =======================================================================================
-- Insert Sample Data: scenario_simulation_v1.Forecast_Metric
-- Generating >100 rows by associating multiple metrics/dates with the simulation runs.
-- =======================================================================================
INSERT INTO `scenario_simulation_v1.Forecast_Metric` (Metric_ID, Simulation_Run_ID, Metric_Name, Projection_Date, Metric_Value, Confidence_Interval_Lower, Confidence_Interval_Upper, Dimension_1_Name, Dimension_1_Value)
VALUES
-- RUN_001 (Capital Stress Test - Baseline) - Monthly projections for Capital Adequacy Ratio (CAR)
('M_001_01', 'RUN_001', 'Capital_Adequacy_Ratio', DATE('2026-06-30'), 1.85, 1.80, 1.90, 'Region', 'EU'),
('M_001_02', 'RUN_001', 'Capital_Adequacy_Ratio', DATE('2026-07-31'), 1.86, 1.81, 1.91, 'Region', 'EU'),
('M_001_03', 'RUN_001', 'Capital_Adequacy_Ratio', DATE('2026-08-31'), 1.84, 1.78, 1.90, 'Region', 'EU'),
('M_001_04', 'RUN_001', 'Capital_Adequacy_Ratio', DATE('2026-09-30'), 1.87, 1.82, 1.93, 'Region', 'EU'),
('M_001_05', 'RUN_001', 'Capital_Adequacy_Ratio', DATE('2026-10-31'), 1.88, 1.82, 1.94, 'Region', 'EU'),
('M_001_06', 'RUN_001', 'Capital_Adequacy_Ratio', DATE('2026-11-30'), 1.87, 1.81, 1.93, 'Region', 'EU'),
('M_001_07', 'RUN_001', 'Capital_Adequacy_Ratio', DATE('2026-12-31'), 1.90, 1.85, 1.95, 'Region', 'EU'),
('M_001_08', 'RUN_001', 'Capital_Adequacy_Ratio', DATE('2027-01-31'), 1.89, 1.83, 1.95, 'Region', 'EU'),
('M_001_09', 'RUN_001', 'Capital_Adequacy_Ratio', DATE('2027-02-28'), 1.91, 1.85, 1.97, 'Region', 'EU'),
('M_001_10', 'RUN_001', 'Capital_Adequacy_Ratio', DATE('2027-03-31'), 1.92, 1.86, 1.98, 'Region', 'EU'),

-- RUN_002 (Capital Stress Test - Adverse Market) - Noticeable drop in CAR
('M_002_01', 'RUN_002', 'Capital_Adequacy_Ratio', DATE('2026-06-30'), 1.65, 1.55, 1.75, 'Region', 'EU'),
('M_002_02', 'RUN_002', 'Capital_Adequacy_Ratio', DATE('2026-07-31'), 1.50, 1.40, 1.60, 'Region', 'EU'),
('M_002_03', 'RUN_002', 'Capital_Adequacy_Ratio', DATE('2026-08-31'), 1.45, 1.35, 1.55, 'Region', 'EU'),
('M_002_04', 'RUN_002', 'Capital_Adequacy_Ratio', DATE('2026-09-30'), 1.42, 1.30, 1.52, 'Region', 'EU'),
('M_002_05', 'RUN_002', 'Capital_Adequacy_Ratio', DATE('2026-10-31'), 1.40, 1.25, 1.50, 'Region', 'EU'),
('M_002_06', 'RUN_002', 'Capital_Adequacy_Ratio', DATE('2026-11-30'), 1.38, 1.20, 1.48, 'Region', 'EU'),
('M_002_07', 'RUN_002', 'Capital_Adequacy_Ratio', DATE('2026-12-31'), 1.35, 1.15, 1.45, 'Region', 'EU'),
('M_002_08', 'RUN_002', 'Capital_Adequacy_Ratio', DATE('2027-01-31'), 1.36, 1.16, 1.46, 'Region', 'EU'),
('M_002_09', 'RUN_002', 'Capital_Adequacy_Ratio', DATE('2027-02-28'), 1.37, 1.18, 1.48, 'Region', 'EU'),
('M_002_10', 'RUN_002', 'Capital_Adequacy_Ratio', DATE('2027-03-31'), 1.40, 1.22, 1.52, 'Region', 'EU'),

-- RUN_003 (Severe Inflation) - Projected Claims Cost (in millions)
('M_003_01', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-06-30'), 45.5, 42.0, 49.0, 'Line_Of_Business', 'Auto'),
('M_003_02', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-07-31'), 47.2, 43.5, 51.0, 'Line_Of_Business', 'Auto'),
('M_003_03', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-08-31'), 49.8, 45.5, 54.0, 'Line_Of_Business', 'Auto'),
('M_003_04', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-09-30'), 52.1, 48.0, 56.5, 'Line_Of_Business', 'Auto'),
('M_003_05', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-10-31'), 54.5, 50.0, 59.0, 'Line_Of_Business', 'Auto'),
('M_003_06', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-11-30'), 56.0, 51.5, 61.0, 'Line_Of_Business', 'Auto'),
('M_003_07', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-12-31'), 58.5, 53.5, 63.5, 'Line_Of_Business', 'Auto'),
('M_003_08', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2027-01-31'), 60.2, 55.0, 65.5, 'Line_Of_Business', 'Auto'),
('M_003_09', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2027-02-28'), 62.8, 57.5, 68.5, 'Line_Of_Business', 'Auto'),
('M_003_10', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2027-03-31'), 65.0, 59.5, 71.0, 'Line_Of_Business', 'Auto'),

('M_003_11', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-06-30'), 30.1, 28.0, 32.5, 'Line_Of_Business', 'Property'),
('M_003_12', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-07-31'), 31.5, 29.5, 34.0, 'Line_Of_Business', 'Property'),
('M_003_13', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-08-31'), 33.2, 31.0, 35.8, 'Line_Of_Business', 'Property'),
('M_003_14', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-09-30'), 35.0, 32.5, 37.5, 'Line_Of_Business', 'Property'),
('M_003_15', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-10-31'), 36.8, 34.0, 39.5, 'Line_Of_Business', 'Property'),
('M_003_16', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-11-30'), 38.5, 36.0, 41.5, 'Line_Of_Business', 'Property'),
('M_003_17', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2026-12-31'), 40.1, 37.5, 43.0, 'Line_Of_Business', 'Property'),
('M_003_18', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2027-01-31'), 42.0, 39.0, 45.0, 'Line_Of_Business', 'Property'),
('M_003_19', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2027-02-28'), 43.5, 40.5, 47.0, 'Line_Of_Business', 'Property'),
('M_003_20', 'RUN_003', 'Projected_Claims_Cost_M', DATE('2027-03-31'), 45.2, 42.0, 49.0, 'Line_Of_Business', 'Property'),

-- RUN_004 (Claims Frequency - Base Trend) - Forecasted Claim Counts per month
('M_004_01', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-06-30'), 12500, 12000, 13000, 'Region', 'North'),
('M_004_02', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-07-31'), 12800, 12200, 13400, 'Region', 'North'),
('M_004_03', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-08-31'), 13100, 12500, 13700, 'Region', 'North'),
('M_004_04', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-09-30'), 13500, 12900, 14100, 'Region', 'North'),
('M_004_05', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-10-31'), 14200, 13500, 14900, 'Region', 'North'), -- Autumn increase
('M_004_06', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-11-30'), 15500, 14800, 16200, 'Region', 'North'), -- Winter onset
('M_004_07', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-12-31'), 16800, 16000, 17600, 'Region', 'North'), -- Peak winter
('M_004_08', 'RUN_004', 'Forecasted_Claim_Count', DATE('2027-01-31'), 16500, 15800, 17200, 'Region', 'North'),
('M_004_09', 'RUN_004', 'Forecasted_Claim_Count', DATE('2027-02-28'), 15000, 14200, 15800, 'Region', 'North'),
('M_004_10', 'RUN_004', 'Forecasted_Claim_Count', DATE('2027-03-31'), 13800, 13100, 14500, 'Region', 'North'),

('M_004_11', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-06-30'), 8500, 8100, 8900, 'Region', 'South'),
('M_004_12', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-07-31'), 8700, 8300, 9100, 'Region', 'South'),
('M_004_13', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-08-31'), 8900, 8500, 9300, 'Region', 'South'),
('M_004_14', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-09-30'), 8800, 8400, 9200, 'Region', 'South'),
('M_004_15', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-10-31'), 9000, 8600, 9400, 'Region', 'South'),
('M_004_16', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-11-30'), 9200, 8800, 9600, 'Region', 'South'),
('M_004_17', 'RUN_004', 'Forecasted_Claim_Count', DATE('2026-12-31'), 9500, 9000, 10000, 'Region', 'South'),
('M_004_18', 'RUN_004', 'Forecasted_Claim_Count', DATE('2027-01-31'), 9400, 8900, 9900, 'Region', 'South'),
('M_004_19', 'RUN_004', 'Forecasted_Claim_Count', DATE('2027-02-28'), 9100, 8700, 9500, 'Region', 'South'),
('M_004_20', 'RUN_004', 'Forecasted_Claim_Count', DATE('2027-03-31'), 8800, 8400, 9200, 'Region', 'South'),

-- RUN_006 (Pricing Elasticity - Target Margin 15%) - Forecasted New Policies
('M_006_01', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-06-30'), 5200, 4900, 5500, 'Product_Tier', 'Basic'),
('M_006_02', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-07-31'), 5350, 5050, 5650, 'Product_Tier', 'Basic'),
('M_006_03', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-08-31'), 5100, 4800, 5400, 'Product_Tier', 'Basic'),
('M_006_04', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-09-30'), 5400, 5100, 5700, 'Product_Tier', 'Basic'),
('M_006_05', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-10-31'), 5600, 5300, 5900, 'Product_Tier', 'Basic'),
('M_006_06', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-11-30'), 5800, 5500, 6100, 'Product_Tier', 'Basic'),
('M_006_07', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-12-31'), 6000, 5700, 6300, 'Product_Tier', 'Basic'),
('M_006_08', 'RUN_006', 'Forecasted_New_Policies', DATE('2027-01-31'), 6200, 5900, 6500, 'Product_Tier', 'Basic'),
('M_006_09', 'RUN_006', 'Forecasted_New_Policies', DATE('2027-02-28'), 6100, 5800, 6400, 'Product_Tier', 'Basic'),
('M_006_10', 'RUN_006', 'Forecasted_New_Policies', DATE('2027-03-31'), 6300, 6000, 6600, 'Product_Tier', 'Basic'),

('M_006_11', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-06-30'), 2100, 1900, 2300, 'Product_Tier', 'Premium'),
('M_006_12', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-07-31'), 2150, 1950, 2350, 'Product_Tier', 'Premium'),
('M_006_13', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-08-31'), 2050, 1850, 2250, 'Product_Tier', 'Premium'),
('M_006_14', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-09-30'), 2200, 2000, 2400, 'Product_Tier', 'Premium'),
('M_006_15', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-10-31'), 2300, 2100, 2500, 'Product_Tier', 'Premium'),
('M_006_16', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-11-30'), 2400, 2200, 2600, 'Product_Tier', 'Premium'),
('M_006_17', 'RUN_006', 'Forecasted_New_Policies', DATE('2026-12-31'), 2500, 2300, 2700, 'Product_Tier', 'Premium'),
('M_006_18', 'RUN_006', 'Forecasted_New_Policies', DATE('2027-01-31'), 2550, 2350, 2750, 'Product_Tier', 'Premium'),
('M_006_19', 'RUN_006', 'Forecasted_New_Policies', DATE('2027-02-28'), 2450, 2250, 2650, 'Product_Tier', 'Premium'),
('M_006_20', 'RUN_006', 'Forecasted_New_Policies', DATE('2027-03-31'), 2600, 2400, 2800, 'Product_Tier', 'Premium'),

-- RUN_008 (Liquidity Forecast - Normal) - Available Cash (in millions)
('M_008_01', 'RUN_008', 'Available_Cash_M', DATE('2026-06-30'), 1500.5, 1450.0, 1550.0, NULL, NULL),
('M_008_02', 'RUN_008', 'Available_Cash_M', DATE('2026-07-31'), 1520.0, 1465.0, 1575.0, NULL, NULL),
('M_008_03', 'RUN_008', 'Available_Cash_M', DATE('2026-08-31'), 1490.2, 1430.0, 1550.0, NULL, NULL),
('M_008_04', 'RUN_008', 'Available_Cash_M', DATE('2026-09-30'), 1515.8, 1455.0, 1580.0, NULL, NULL),
('M_008_05', 'RUN_008', 'Available_Cash_M', DATE('2026-10-31'), 1540.1, 1480.0, 1600.0, NULL, NULL),
('M_008_06', 'RUN_008', 'Available_Cash_M', DATE('2026-11-30'), 1530.5, 1470.0, 1590.0, NULL, NULL),
('M_008_07', 'RUN_008', 'Available_Cash_M', DATE('2026-12-31'), 1580.0, 1510.0, 1650.0, NULL, NULL),
('M_008_08', 'RUN_008', 'Available_Cash_M', DATE('2027-01-31'), 1560.3, 1495.0, 1625.0, NULL, NULL),
('M_008_09', 'RUN_008', 'Available_Cash_M', DATE('2027-02-28'), 1555.0, 1490.0, 1620.0, NULL, NULL),
('M_008_10', 'RUN_008', 'Available_Cash_M', DATE('2027-03-31'), 1590.7, 1520.0, 1660.0, NULL, NULL),

-- RUN_009 (Lapse Rate Predictor - Recession) - Forecasted Lapse Rate Percentage
('M_009_01', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-06-30'), 8.5, 7.5, 9.5, 'Sales_Channel', 'Broker'),
('M_009_02', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-07-31'), 8.8, 7.8, 9.8, 'Sales_Channel', 'Broker'),
('M_009_03', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-08-31'), 9.2, 8.1, 10.3, 'Sales_Channel', 'Broker'),
('M_009_04', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-09-30'), 9.5, 8.4, 10.6, 'Sales_Channel', 'Broker'),
('M_009_05', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-10-31'), 10.1, 8.9, 11.3, 'Sales_Channel', 'Broker'),
('M_009_06', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-11-30'), 10.5, 9.3, 11.7, 'Sales_Channel', 'Broker'),
('M_009_07', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-12-31'), 11.2, 9.9, 12.5, 'Sales_Channel', 'Broker'),
('M_009_08', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2027-01-31'), 11.5, 10.2, 12.8, 'Sales_Channel', 'Broker'),
('M_009_09', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2027-02-28'), 11.8, 10.5, 13.1, 'Sales_Channel', 'Broker'),
('M_009_10', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2027-03-31'), 12.1, 10.8, 13.4, 'Sales_Channel', 'Broker'),

('M_009_11', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-06-30'), 6.2, 5.5, 6.9, 'Sales_Channel', 'Direct'),
('M_009_12', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-07-31'), 6.5, 5.7, 7.3, 'Sales_Channel', 'Direct'),
('M_009_13', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-08-31'), 6.8, 6.0, 7.6, 'Sales_Channel', 'Direct'),
('M_009_14', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-09-30'), 7.1, 6.3, 7.9, 'Sales_Channel', 'Direct'),
('M_009_15', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-10-31'), 7.4, 6.6, 8.2, 'Sales_Channel', 'Direct'),
('M_009_16', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-11-30'), 7.7, 6.8, 8.6, 'Sales_Channel', 'Direct'),
('M_009_17', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2026-12-31'), 8.0, 7.1, 8.9, 'Sales_Channel', 'Direct'),
('M_009_18', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2027-01-31'), 8.3, 7.4, 9.2, 'Sales_Channel', 'Direct'),
('M_009_19', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2027-02-28'), 8.5, 7.6, 9.4, 'Sales_Channel', 'Direct'),
('M_009_20', 'RUN_009', 'Forecasted_Lapse_Rate_Pct', DATE('2027-03-31'), 8.8, 7.8, 9.8, 'Sales_Channel', 'Direct'),

-- RUN_010 (Lapse Rate Predictor - Optimistic) - Forecasted Lapse Rate Percentage
('M_010_01', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-06-30'), 5.5, 4.8, 6.2, 'Sales_Channel', 'Broker'),
('M_010_02', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-07-31'), 5.3, 4.6, 6.0, 'Sales_Channel', 'Broker'),
('M_010_03', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-08-31'), 5.1, 4.4, 5.8, 'Sales_Channel', 'Broker'),
('M_010_04', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-09-30'), 4.9, 4.2, 5.6, 'Sales_Channel', 'Broker'),
('M_010_05', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-10-31'), 4.8, 4.1, 5.5, 'Sales_Channel', 'Broker'),
('M_010_06', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-11-30'), 4.7, 4.0, 5.4, 'Sales_Channel', 'Broker'),
('M_010_07', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-12-31'), 4.5, 3.8, 5.2, 'Sales_Channel', 'Broker'),
('M_010_08', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2027-01-31'), 4.4, 3.7, 5.1, 'Sales_Channel', 'Broker'),
('M_010_09', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2027-02-28'), 4.3, 3.6, 5.0, 'Sales_Channel', 'Broker'),
('M_010_10', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2027-03-31'), 4.2, 3.5, 4.9, 'Sales_Channel', 'Broker'),

('M_010_11', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-06-30'), 4.0, 3.5, 4.5, 'Sales_Channel', 'Direct'),
('M_010_12', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-07-31'), 3.9, 3.4, 4.4, 'Sales_Channel', 'Direct'),
('M_010_13', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-08-31'), 3.8, 3.3, 4.3, 'Sales_Channel', 'Direct'),
('M_010_14', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-09-30'), 3.7, 3.2, 4.2, 'Sales_Channel', 'Direct'),
('M_010_15', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-10-31'), 3.6, 3.1, 4.1, 'Sales_Channel', 'Direct'),
('M_010_16', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-11-30'), 3.5, 3.0, 4.0, 'Sales_Channel', 'Direct'),
('M_010_17', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2026-12-31'), 3.4, 2.9, 3.9, 'Sales_Channel', 'Direct'),
('M_010_18', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2027-01-31'), 3.3, 2.8, 3.8, 'Sales_Channel', 'Direct'),
('M_010_19', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2027-02-28'), 3.2, 2.7, 3.7, 'Sales_Channel', 'Direct'),
('M_010_20', 'RUN_010', 'Forecasted_Lapse_Rate_Pct', DATE('2027-03-31'), 3.1, 2.6, 3.6, 'Sales_Channel', 'Direct');